package com.simplemobiletools.musicplayer.helpers

val PREFS = "prefs"
val WIDGET_BG_COLOR = "widget_bg_color"
val WIDGET_TEXT_COLOR = "widget_text_color"
val SONG_POS = "song_position"
val PROGRESS = "progress"
val DELETED_SONGS = "deleted_songs"
val EDITED_SONG = "edited_song"
val UPDATE_ACTIVITY = "update_activity"

private val PATH = "com.simplemobiletools.musicplayer.action."

val INIT = PATH + "INIT"
val FINISH = PATH + "FINISH"
val PREVIOUS = PATH + "PREVIOUS"
val PAUSE = PATH + "PAUSE"
val PLAYPAUSE = PATH + "PLAYPAUSE"
val NEXT = PATH + "NEXT"
val EDIT = PATH + "EDIT"
val PLAYPOS = PATH + "PLAYPOS"
val REFRESH_LIST = PATH + "REFRESH_LIST"
val CALL_START = PATH + "CALL_START"
val CALL_STOP = PATH + "CALL_STOP"
val SET_PROGRESS = PATH + "SET_PROGRESS"
val SET_EQUALIZER = PATH + "SET_EQUALIZER"

// shared preferences
val PREFS_KEY = "Music Player"
val IS_FIRST_RUN = "is_first_run"
val IS_DARK_THEME = "is_dark_theme"
val SHUFFLE = "shuffle"
val NUMERIC_PROGRESS = "numeric_progress"
val SORTING = "sorting"
val EQUALIZER = "equalizer"
val REPEAT_SONG = "repeat_song"
